### ISSUE TITLE
Dataset application

### ISSUE THREAD

**Issue by Van-NguyenPham** [WeiQijie/retinal-lesions#3]
Dear authors,
I submitted a request for the dataset via google form. Could you please accept my application? Thank you very much.

**Comment by leigaoyi** [comment]
你好，请问你需要的具体是哪个项目？眼底图像的血管分割和DR分割，我用的都是公开数据集，比如：
https://ieee-dataport.org/open-access/indian-diabetic-retinopathy-image-dataset-idrid
https://idrid.grand-challenge.org/


希望我的回复有帮到你，
高益













At 2021-04-26 08:16:25, "Nguyen" ***@***.***> wrote:

Dear authors,
I submitted a request for the dataset via google form. Could you please accept my application? Thank you very much.
