### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by WHloveHZN** [WeiQijie/retinal-lesions#5]
I greatly appreciate the author's contribution to the dataset.
I have already submitted a request for the dataset. When will I receive the download link?
Thank you again.

**Comment by WeiQijie** [comment]
> I greatly appreciate the author's contribution to the dataset. I have already submitted a request for the dataset. When will I receive the download link? Thank you again.

I will remaind the corresponding author to check the request. He might be a bit busy these days.

**Comment by twmht** [comment]
@WeiQijie 

plz help to check my request to the dataset, my email is  m013040008@student.nsysu.edu.tw

**Comment by yanglei1111** [comment]
@WeiQijie Hello, I have also submitted a request for the dataset. Could you please help check the status of my request? My email is yanglei@std.uestc.edu.cn. Thank you very much for your assistance!

**Comment by WeiQijie** [comment]
> [@WeiQijie](https://github.com/WeiQijie) Hello, I have also submitted a request for the dataset. Could you please help check the status of my request? My email is [yanglei@std.uestc.edu.cn](mailto:yanglei@std.uestc.edu.cn). Thank you very much for your assistance!

Sorry for the delay. I will remind the responsible person to check the request.
